# simulates a dichotomous phenotype that is related to a genotype expressed
# as an allele count for three siblings suitable for OLS, FE, or phenotype
# differences estimation
#
# dichotomous phenotypes are generated by using a linear causal model within
# a standard logistic sigmoid to generate probability of expressing phenotype 1
# and and treating phenotype as a bernoulli trial
#
# inputs:
#   N - number of sibling triplets
#   rho_g - genetic correlation in parent's generation (not implemented)
#   p_allele - allele prevalence in parent's generation
#   alpha - controls phenotype prevalence
#   beta - magnitude of direct genetic effect within GLM
#   gamma_1 - standard deviation of family environment effect distribution
#   gamma_2 - standard deviation of individual environment effect distribution
#
# outputs:
#   dataframe with:
#     g_m/g_p - maternal and paternal genotypes
#     g0/g1/g2 - sibling genotypes
#     eps_fam - family environment
#     Y0/Y1/Y2 - sibling phenotypes


sim.allele.dich <- function(N=1e5, rho_g=0.3, p_allele=0.3,
                           alpha=-1, beta=0.04,
                           gamma_1=sqrt(0.35), gamma_2=sqrt(0.649)){

  sim.genes <- function(N=N, rho=rho, rho_g=rho_g, p_allele=p_allele){
    g_m <- rbinom(n=N, size=2, prob=p_allele)
    g_p <- rbinom(n=N, size=2, prob=p_allele)

    out <- data.frame(g_m = g_m,
                      g_p = g_p,
                      g0 = rbinom(N, 1, g_m/2) + rbinom(N, 1, g_p/2),
                      g1 = rbinom(N, 1, g_m/2) + rbinom(N, 1, g_p/2),
                      g2 = rbinom(N, 1, g_m/2) + rbinom(N, 1, g_p/2),
                      eps_fam = rnorm(N))
    return(out)
  }

  sigmoid <- function(z){
    out <- 1 / (1 + exp(-z))
  }

  d <- sim.genes(N=N, rho=rho, rho_g=rho_g, p_allele=p_allele)

  p0 <- sigmoid(alpha + beta*d$g0 + gamma_1*d$eps_fam + gamma_2*rnorm(N))
  p1 <- sigmoid(alpha + beta*d$g1 + gamma_1*d$eps_fam + gamma_2*rnorm(N))
  p2 <- sigmoid(alpha + beta*d$g2 + gamma_1*d$eps_fam + gamma_2*rnorm(N))

  d$Y0 <- rbinom(N, 1, p0)
  d$Y1 <- rbinom(N, 1, p1)
  d$Y2 <- rbinom(N, 1, p2)

  return(d)
}
